<a href="https://colab.research.google.com/github/miran060/bigbata-programming/blob/main/03w_numpy_handie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 다차원 배열 ndarray

In [ ]:
import numpy as np

a = np.ndarray((2, 3))
a

array([[2.07777958e-315, 0.00000000e+000, 6.81289640e-310],
       [5.36368732e-317, 5.37026432e-317, 6.81289644e-310]])

In [ ]:
import numpy as np

a = np.ndarray((3, 2), dtype=int)
a

array([[      420547268,               0],
       [137894558329200,        10856224],
       [       10869536, 137894559021040]])

In [ ]:
a = np.ndarray((3, 2), int)
a

array([[      471930229,               0],
       [137893869680320, 137894748235248],
       [137894748235248, 137894748235248]])

### 내장함수 array()

In [ ]:
import numpy as np
a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [ ]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


### 문자열 자료형

In [ ]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
import numpy as np

unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
unicode_array = np.array(['가나다라마'*7, '라바마', '사아자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라바마', '사아자'], dtype='<U32')

### numpy.arange() 실수도 가능

In [ ]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [ ]:
import numpy as np

print(np.arange(2, 0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


### 배열의 모양 바꾸는 reshape()

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.reshape(a, (2, 6
               ))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
np.reshape(a, (3, 5))  #오류가 뜰지두..

ValueError: cannot reshape array of size 12 into shape (3,5)

### 함수 linspace()
교재 p89~90

In [ ]:
import numpy as np
np.linspace(2, 3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
(3-1)/(50-1)

0.04081632653061224

In [ ]:
np.linspace(2, 3, 2)

array([2., 3.])

In [ ]:
np.linspace(2, 3, 3)

array([2. , 2.5, 3. ])

In [ ]:
np.linspace(2, 3, 3, retstep=True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [ ]:
np.linspace(2, 3, 3, retstep = True, endpoint=False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [ ]:
(3-2)/3

0.3333333333333333

In [ ]:
np.linspace(2, 3, 3)

array([2. , 2.5, 3. ])

### numpy.full

In [ ]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.full([2, 3], (1, 2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [ ]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.full((4, 3), np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### 지정한 모양의 배열을 생성하는 numpy.empty(shape)

In [ ]:
np.empty(3)

array([2. , 2.5, 3. ])

In [ ]:
np.empty([2,2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [ ]:
np.empty([2, 3], dtype = int)

array([[      420547268,               0, 137894558329200],
       [       10856224,        10869536, 137894559021040]])

원소값이 0인 주어진 형태의 배열을 생성하는 zeros_like(a)

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

원소값이 1인 주어진 형태의 배열을 생성하는 ones_like()

In [ ]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

원소값이 주어진 값이며 주어진 형태의 배열을 생성하는 full_like()

In [ ]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

### 배열과 스칼라의 연산

In [ ]:
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


### 배열 함수

In [ ]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [ ]:
a.sum()

np.int64(46)

In [ ]:
a.sum(axis=0)

array([16, 30])

In [ ]:
a.sum(axis=1)

array([30, 13,  3])

In [ ]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46


TypeError: sum() got an unexpected keyword argument 'sxis'

### 1차원 배열의 첨자와 슬라이싱

In [ ]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[3])
print(a[-2])

9
64


In [ ]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [ ]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


역순과 대입

In [ ]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [ ]:
a[::-2]

#실수로 {} 이걸 사용했었더니 에러가 났었음

array([  81,   49,   25, -100,    1])

In [ ]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [ ]:
a[2:5] = [-5, -5]
a

#대입할 원소 수가 3개 이어야 함

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [ ]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

### 2차원 배열의 첨자와 슬라이싱

In [ ]:
a = np.arange(30).reshape(5, 6)

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [ ]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[1: 5: 2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[, 1]

# 비우면 오류가 난다

SyntaxError: invalid syntax (3063698125.py, line 1)

In [ ]:
ㅁ[:, 1]

NameError: name 'ᄆ' is not defined

In [ ]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [ ]:
a = np.arange(30).reshape(5, 6)
a

#ppt.p43 시험문제에 내기 좋

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
a[2, 4]

np.int64(16)

In [ ]:
a[2][4]

np.int64(16)

In [ ]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [ ]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:

a[::-1, ::-1]


# 시험문제에 이런 것을 출재한다 함

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
## 마지막 행과 열을 제외한 배열 반환
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

# 3차원 배열의 다양한 참조

In [ ]:
a[1]

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
a[:,1]

array([ 1,  7, 13, 19, 25])

In [ ]:
a[:,1,1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
a[:, :, 1]


# 왜 안되는건지 gpt 검색을 해봤지만 확답을 받지 못함

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

### 1차원 배열로 만드는 ndarray.ravel()

In [ ]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

np.transpose(a)와 a.transpose(), a.T #전치행렬

In [ ]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

3차원 배열에서 swapaxes()

In [ ]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [ ]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

보기(view)

In [ ]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [ ]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [ ]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [ ]:
org

array([  0,   1, 200,   3,   4])

복사(copy)

In [ ]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [ ]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [ ]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [ ]:
org

array([0, 1, 2, 3, 4])

# 브로드캐스팅 p.62(ppt)

In [ ]:
a = np.array([4, 5, 6])
b = np.array([8, 7, 6])
a + b

array([12, 12, 12])

In [ ]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = arange(-1 , 2)
y

array([-1,  0,  1])

# 고급 색인

ppt p.70

In [ ]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1]

#이런건 그냥 원소값이 나오고

np.int64(1)

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[ [2] ]



array([2])

In [ ]:
x[ [2, 3]]

#나열 인덱스로 나열을 갖는 배열이라고 함

array([2, 3])

In [ ]:
x[ [2, 3, 2, 5, 8]]

array([2, 3, 2, 5, 8])

In [ ]:
x[     2:8]

array([[7, 8, 9]])

In [ ]:
x[0,1]

np.int64(2)

In [ ]:
x[ [0, 1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[ [0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
from numpy import arange
x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[ [1, 3, 5]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x[ [1, 3, 5], : ]

# 바로 위에거랑 따로 차이가 없어서 얘나 얘나 거기서 거기다.

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x[[1, 3], [2, 2]]

array([10, 26])

In [ ]:
x[[1, 3], [2, 2], [3, 3]]

#원소가 제대로 매칭이 안되면 오류가 난다.

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
from numpy import arange
x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
from numpy import arange
x- arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [1, 3], [2] ]

array([10, 26])

In [ ]:
x[ [1,3], [2, 3]]

array([10, 27])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0, 2, 4], [1]]

array([ 1, 17, 33])

In [ ]:
x[ [0, 2, 4], :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
x[ [0, 2, 4], [1, 1, 1] ]

array([ 1, 17, 33])

In [ ]:
x[ [0, 2, 4], [1, 1]]


#안되는게 당연함. 이런거 많이 연습해보기

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [ ]:
a

array([4, 5, 6])

In [ ]:
from numpy import arange
a= arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a[arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
from numpy import arange
a=arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[np.arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [ ]:
a[np.arange(2, 4)][:, [1, 1, 1]]

array([[17, 17, 17],
       [25, 25, 25]])

In [ ]:
a[np.arange(2, 4)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [ ]:
a[[2, 3, 4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

#종료