<a href="https://colab.research.google.com/github/miran060/bigbata-programming/blob/main/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

np.stack((arr_1, arr_2), axid = )

In [2]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [4]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

np.column_stack()

In [89]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
c = np.arange(1, 6, 2)
print(c)

[1 3 5]


In [20]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [17]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6] )

np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
np.column_stack( (a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])
x

array([[1, 2, 3]])

In [24]:
y

array([[4, 5, 6]])

In [25]:
x.shape, y.shape

((1, 3), (1, 3))

In [26]:
np.column_stack( (x, y))

array([[1, 2, 3, 4, 5, 6]])

In [27]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [28]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [29]:
np.column_stack( (x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

### 난수 기초

In [46]:
import numpy as np

rg = np.random.default_rng(12345)  # 생성자에서 값을주면
rg.random()  # [0, 1)
# random을 붙여도 값은 같게 나오는걸 볼수 있음 / 제너레이터를 만들고 해서 랜덤을 해도 값은 똑같이 나오는 것이다

0.22733602246716966

In [59]:
rg.random()

0.09589793559411208

In [65]:
rg.random(5) # 하나 쓰면 1차원

array([0.27377318, 0.45177871, 0.66503892, 0.33089093, 0.90345401])

In [69]:
rg.random( (3, 4)) #2개 쓰면 2차원 배열


array([[0.47636886, 0.25523235, 0.29756527, 0.27906712],
       [0.26057921, 0.48276159, 0.21197904, 0.4956306 ],
       [0.24626133, 0.83848265, 0.18013059, 0.86215629]])

In [70]:
rg.random( (2, 3, 4)) # 3개 써주면 3차원 배열

array([[[0.17829944, 0.75053133, 0.6111204 , 0.20915503],
        [0.75987242, 0.24926057, 0.08557173, 0.61805672],
        [0.53696833, 0.63452671, 0.17437411, 0.24816449]],

       [[0.68482298, 0.08087165, 0.8750736 , 0.42869438],
        [0.6183942 , 0.3131055 , 0.17896286, 0.00971213],
        [0.21004296, 0.87000068, 0.9728298 , 0.44179234]]])

In [68]:
rg.random(5)

array([0.30438839, 0.44088681, 0.15020234, 0.21792886, 0.47433312])

In [71]:
import numpy as np

rg = np.random.default_rng(1)
rg.integers(low=0, high=10, size=3) # [0, 10) 정수 난수
  # 항상 값은 똑같음

array([4, 5, 7])

In [77]:
rg.integers(low=0, high=20, size=(3, 4))

# 값은 랜덤이다

array([[14,  5, 10, 18],
       [ 5, 14,  3,  6],
       [19,  8, 10,  5]])

In [81]:
rg.integers(0, 20, size=(3, 4))

#이것도 랜덤

array([[16,  1, 13, 15],
       [15, 17,  3, 11],
       [16,  7,  3,  9]])

In [85]:
rg.integers(1, 7, (3, 4))

#이것도 랜덤

array([[3, 4, 4, 6],
       [1, 3, 5, 3],
       [6, 6, 5, 3]])

In [87]:
import numpy as np

rg = np.random.default_rng(1)
rg.standard_normal(3) # 표준 정규분포 실수 난수

array([0.34558419, 0.82161814, 0.33043708])

In [97]:
rg.standard_normal((3, 4)) # 표준 정규분포 실수 난수

# 오류가 났던 이유 : ( ( ) ) 이렇게 안하고 () 이거 하나만 적어서
# 이런 오타 많이 나오니 주의 필요......



# ++ 3 넘어가는 건 거의 없고 대부분 2에서 끝남. 95% 확률로
# -9 까지 나온거 확인해봄

array([[-1.04879657e-03,  4.45573554e-01,  4.68404336e-01,
         8.76242196e-01],
       [ 2.56485627e-01, -9.48283390e-02, -2.58848065e-01,
         1.05574280e+00],
       [-2.25085428e+00, -1.38655325e-01,  3.30001040e-02,
        -1.42534896e+00]])

### 배열 결합 연습

In [98]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.arange(7, 10)
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [100]:
p = np.arange(1, 7).reshape(2, 3)
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)

p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [101]:
np.vstack( (a, b, c)) # 10 --> 20

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
np.vstack( (p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [103]:
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [104]:
a,b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [106]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [107]:
np.column_stack((p, q, r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [111]:
np.concatenate((a, b, c), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [112]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
np.concatenate((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [114]:
np.concatenate((p, q, r), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [116]:
np.concatenate((p, q, r), axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [115]:
np.concatenate((p, q, r), axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [117]:
np.c_[a, b, c] #10 -> 20

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [119]:
np.c_[(a, b, c)] #10 -> 20
# 괄호를 써도 똑같이 돌아가긴 함

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [122]:
np.column_stack( (a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [125]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [123]:
np.c_[p, q, r]

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [124]:
np.r_[p, q, r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [126]:
np.vstack((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])